### ***Import Libraries***

In [ ]:
# Packages for EDA (Exploratory Data Analyst)
import pandas as pd
import numpy as np

# Load Data
from google.colab import drive
import os

# For data
import random
import string
import re

from time import time
import tf_slim as slim

### ***Data Extraction from Gdrive***

#### *Mount to Drive*

In [ ]:
# Connect to drive
drive.mount('/content/drive')

Mounted at /content/drive


#### Inisialisasi Path

In [ ]:
# Inisialisasi path data half preprocessed
path = '/content/drive/My Drive/Tuhan_Yesus_tolong_skripsi_dek_Doma/data/fix/data_v5.csv'

In [ ]:
df = pd.read_csv(path, na_filter=True, na_values='[]')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   rating               3000 non-null   int64 
 1   teks-review-fix      3000 non-null   object
 2   img-caption          3000 non-null   object
 3   category             3000 non-null   object
 4   review-with-caption  3000 non-null   object
dtypes: int64(1), object(4)
memory usage: 117.3+ KB


In [ ]:
import re

def strip_whitespaces(string):
  res = re.sub(' +', ' ', string)
  return res

# for index, s in df['teks-review-fix']:
#   s = strip_whitespaces(s)
df['teks-review-fix'] = df['teks-review-fix'].apply(lambda x: strip_whitespaces(x))

In [ ]:
df['review-with-caption'] = df['review-with-caption'].apply(lambda x: strip_whitespaces(x))

In [ ]:
for s in df['teks-review-fix']:
  print(s)

produk sangat bagus bahan juga adem pengiriman cepat kurir ramah sangat baik lah
tampilan sesua di foto warna bagus bahan bagus lumayan tebal biasa pakai 30 tetapi ini saya pesan ukuran 31 tetapi masih nyaman dipakai tidak kecewa rekomendasi senang netral
kancing terlepas bahan gampang menempel bulu bulu tetapi tertolong dan ikat pinggang orisinal dari terima kasih
tampilan bagus warna sesuai cocok untuk aktivitas sehari hari termasuk semi formal
tampilan bahan lembut saya suka ini warna hitam cokelat susu l
produk sesuai deskripsi ukuran sesuai jahitan rapi dan bahan nyaman dipakai puas dengan pelayanan prima dan pengiriman yang sangat baik toko rekomendasi dan lanjut beli
tampilan bagus banget warna toplah sesuai harapan potongan tidak pernah membuat kecewa
kualitas produk bagus bahan tebal bagus untuk harga di bawah 100k tetapi terdapat bintik cokelat di seluruh bagian celana tetapi keseluruhan bagus
tampilan bagus warna denim l bagus sesuai deskripsi semoga pas dan dia suka bagus b

In [ ]:
!pip install vaderSentiment

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 2.5 MB/s eta 0:00:00


In [ ]:
# import stopwords from nltk corpus
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

from nltk.corpus import stopwords
analyzer = SentimentIntensityAnalyzer()

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
# Negation words handling for stopwords removal function

def stopwords_neg_handling():
  # Get list of stopwords from nltk
  sw = list(stopwords.words('indonesian'))

  # Make a list of negation words
  neg_words = negation_word = ['tidak', 'usah', 'mesti', 'jangan', 'bukan', 'enggak', 'tak', 'tanpa', 'ngga', 'ga', 'tempat', 'baik', 'lebih', 'sekitar', 'kira', 'kira-kira']

  # Make a new list to handle the negation words
  fix_stopwords = []

  i = 0
  j = 0
  for word in sw:
    if word not in neg_words:
      fix_stopwords.append(word)
      i = i + 1
    else:
      j = j + 1

  return fix_stopwords

In [ ]:
pip install sastrawi

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 1.7 MB/s eta 0:00:00


In [ ]:
stopwords_fix = stopwords_neg_handling()

In [ ]:
# Stopwords removal function

def remove_stopwords(text, stopwords):

  return " ".join([word for word in str(text).split() if word not in stopwords])

In [ ]:
df['teks-review-fix'] = df['teks-review-fix'].apply(lambda x: remove_stopwords(x, stopwords_fix))

In [ ]:
df['review-with-caption'] = df['review-with-caption'].apply(lambda x: remove_stopwords(x, stopwords_fix))

In [ ]:
for s in df['teks-review-fix']:
  print(s)

produk bagus bahan adem pengiriman cepat kurir ramah baik
tampilan sesua foto warna bagus bahan bagus lumayan tebal pakai 30 pesan ukuran 31 nyaman dipakai tidak kecewa rekomendasi senang netral
kancing terlepas bahan gampang menempel bulu bulu tertolong ikat pinggang orisinal terima kasih
tampilan bagus warna sesuai cocok aktivitas sehari semi formal
tampilan bahan lembut suka warna hitam cokelat susu l
produk sesuai deskripsi ukuran sesuai jahitan rapi bahan nyaman dipakai puas pelayanan prima pengiriman baik toko rekomendasi beli
tampilan bagus banget warna toplah sesuai harapan potongan tidak kecewa
kualitas produk bagus bahan tebal bagus harga 100k bintik cokelat celana bagus
tampilan bagus warna denim l bagus sesuai deskripsi semoga pas suka bagus banget 🫶 netral🫶 netral🫶 netral🫶 netral
warna abu-abu dicuci semoga tidak luntur tampilan oke banget bagus banget nyaman kain tidak kaku elastis stiker saku penyimpanan ponsel jahitan rapi adem beli berat badan 70 sarankan xl xxl
perfor

In [ ]:
df.to_csv('/content/drive/My Drive/Tuhan_Yesus_tolong_skripsi_dek_Doma/data/fix/data_v6.csv', index=False)

In [ ]:
df

rating                                    teks-review-fix  \
0          2  produk bagus bahan adem pengiriman cepat kurir...   
1          2  tampilan sesua foto warna bagus bahan bagus lu...   
2          2  kancing terlepas bahan gampang menempel bulu b...   
3          2  tampilan bagus warna sesuai cocok aktivitas se...   
4          2  tampilan bahan lembut suka warna hitam cokelat...   
...      ...                                                ...   
2995       2  bagus banget asli sumpah tidak sesal bahan lem...   
2996       2  enak bagus pengiriman cepat super cepat pakai ...   
2997       2  tampilan oke warna sesuai pesanan syukur paket...   
2998       2  suka banget warnanya bagus kalem kain adem nya...   
2999       2  barang sesuai pesanan bahan oxford lembut nyam...   

                                            img-caption       category  \
0                       beberapa tas duduk di atas meja  celana_wanita   
1                     seseorang memegang label di jaket  celana_wanita   
2           seseorang memegang gunting di tangan mereka  celana_wanita   
3        sepasang celana pria duduk di atas lantai kayu  celana_wanita   
4       sepasang celana tergeletak di atas tempat tidur  celana_wanita   
...                                                 ...            ...   
2995       close up kemeja biru dengan label di atasnya    kemeja_pria   
2996              close up kemeja dengan tag di atasnya    kemeja_pria   
2997           kemeja merah dengan dasi di tempat tidur    kemeja_pria   
2998       kemeja merah muda duduk di atas lantai merah    kemeja_pria   
2999  seorang pria berdiri di sebuah ruangan dengan ...    kemeja_pria   

                                    review-with-caption  
0     produk bagus bahan adem pengiriman cepat kurir...  
1     tampilan sesua foto warna bagus bahan bagus lu...  
2     kancing terlepas bahan gampang menempel bulu b...  
3     tampilan bagus warna sesuai cocok aktivitas se...  
4     tampilan bahan lembut suka warna hitam cokelat...  
...                                                 ...  
2995  bagus banget asli sumpah tidak sesal bahan lem...  
2996  enak bagus pengiriman cepat super cepat pakai ...  
2997  tampilan oke warna sesuai pesanan syukur paket...  
2998  suka banget warnanya bagus kalem kain adem nya...  
2999  barang sesuai pesanan bahan oxford lembut nyam...  

[3000 rows x 5 columns]

### ***Train-Test Split***

In [ ]:
# Split the data into text and labels
X = df['teks-review-fix'].values
X_cap = df['review-with-caption'].values
y = df['rating'].values

#### *Split X into Train and Test Set*

In [ ]:
from sklearn.model_selection import train_test_split

# Assume X is the feature matrix and y is the target vector with sentiment labels

# Split the data into train and test sets with stratified sampling
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=37, stratify=y)

In [ ]:
print("X_train shape: ", X_train.shape)
print("X_test shape: ", X_test.shape)

X_train shape:  (2700,)
X_test shape:  (300,)


#### *Split X_rev_cap into Train and Test Set*

In [ ]:
from sklearn.model_selection import train_test_split

# Assume X is the feature matrix and y is the target vector with sentiment labels

# Split the data into train and test sets with stratified sampling
X_train_cap, X_test_cap, y_train_cap, y_test_cap = train_test_split(X_cap, y, test_size=0.1, random_state=37, stratify=y)

In [ ]:
print("X_train_cap shape: ", X_train_cap.shape)
print("X_test_cap shape: ", X_test_cap.shape)

X_train_cap shape:  (2700,)
X_test_cap shape:  (300,)


### ***Tokenize***

##### *Tokenize train set - just review*

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tokenize reviews without img caption
tokenizer_train = Tokenizer(num_words=150, oov_token="<OOV>")
tokenizer_train.fit_on_texts(X_train)
word_index_train = tokenizer_train.word_index

# Make a sequence of train set reviews without img caption
sequences_train = tokenizer_train.texts_to_sequences(X_train)

In [ ]:
print(max(len(seq) for seq in sequences_train))

131


In [ ]:
# Pad the sequence
padded_seq_train = pad_sequences(sequences_train, padding='post', truncating='post', maxlen=134)
# print(max(len(seq) for seq in padded_seq_train_reviews))

In [ ]:
# Define the batch_size of tokenized sequences train reviews data
batch_size_train = 64
# Define the sequence length of tokenized sequences train reviews data
seq_len_train = max(len(seq) for seq in padded_seq_train)

In [ ]:
print(seq_len_train)
# print(batch_size_train_reviews)
# batch_size_train_reviews

134


In [ ]:
padded_seq_train

array([[68,  1, 20, ...,  0,  0,  0],
       [32, 10,  1, ...,  0,  0,  0],
       [ 8, 21,  4, ...,  0,  0,  0],
       ...,
       [ 4, 90,  1, ...,  0,  0,  0],
       [90,  1, 80, ...,  0,  0,  0],
       [ 8,  3,  4, ...,  0,  0,  0]], dtype=int32)

##### *Tokenize train set - review with caption*

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tokenize reviews without img caption
tokenizer_train_cap = Tokenizer(num_words=150, oov_token="<OOV>")
tokenizer_train_cap.fit_on_texts(X_train_cap)
word_index_train_cap = tokenizer_train_cap.word_index

# Make a sequence of train set reviews without img caption
sequences_train_cap = tokenizer_train_cap.texts_to_sequences(X_train_cap)

In [ ]:
print(max(len(seq) for seq in sequences_train_cap))

135


In [ ]:
# Pad the sequence
padded_seq_train_cap = pad_sequences(sequences_train_cap, padding='post', truncating='post', maxlen=140)
# print(max(len(seq) for seq in padded_seq_train_reviews_caption))

In [ ]:
# Define the batch_size of tokenized sequences train reviews data
batch_size_train_cap = 64
# Define the sequence length of tokenized sequences train reviews data
seq_len_train_cap = max(len(seq) for seq in padded_seq_train_cap)

In [ ]:
print(padded_seq_train_cap)
# print(batch_size_train_reviews)
# batch_size_train_reviews

[[101   1  34 ...   0   0   0]
 [ 47  15   1 ...   0   0   0]
 [  8  38   4 ...   0   0   0]
 ...
 [  4  49   1 ...   0   0   0]
 [ 49   1  52 ...   0   0   0]
 [  8   3   4 ...   0   0   0]]


##### *Tokenize test set - just review*

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tokenize reviews without img caption
tokenizer_test = Tokenizer(num_words=150, oov_token="<OOV>")
tokenizer_test.fit_on_texts(X_test)
word_index_test = tokenizer_test.word_index

# Make a sequence of test set reviews without img caption
sequences_test = tokenizer_test.texts_to_sequences(X_test)

In [ ]:
print(max(len(seq) for seq in sequences_test))

41


In [ ]:
# Pad the sequence
padded_seq_test = pad_sequences(sequences_test, padding='post', truncating='post', maxlen=134)

In [ ]:
# print(max(len(seq) for seq in padded_seq_test_reviews))

In [ ]:
# Define the batch_size of tokenized sequences test_reviews data
batch_size_test = 64
# Define the sequence length of tokenized sequences test data
seq_len_test = max(len(seq) for seq in padded_seq_test)

In [ ]:
print(padded_seq_test)

[[102   6   2 ...   0   0   0]
 [  3  22   1 ...   0   0   0]
 [  8  11   1 ...   0   0   0]
 ...
 [ 53  90  46 ...   0   0   0]
 [ 26  40   3 ...   0   0   0]
 [  8   7   4 ...   0   0   0]]


##### *Tokenize test set - review with caption*

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tokenize reviews without img caption
tokenizer_test_cap = Tokenizer(num_words=150, oov_token="<OOV>")
tokenizer_test_cap.fit_on_texts(X_test_cap)
word_index_test_cap = tokenizer_test.word_index

# Make a sequence of test set reviews without img caption
sequences_test_cap = tokenizer_test_cap.texts_to_sequences(X_test_cap)

In [ ]:
print(max(len(seq) for seq in sequences_test_cap))

46


In [ ]:
# Pad the sequence
padded_seq_test_cap = pad_sequences(sequences_test_cap, padding='post', truncating='post', maxlen=140)

In [ ]:
# print(max(len(seq) for seq in padded_seq_test_reviews_caption))

In [ ]:
# Define the batch_size of tokenized sequences test_reviews data
batch_size_test_cap = 64
# Define the sequence length of tokenized sequences reviews data
seq_len_test_cap = max(len(seq) for seq in padded_seq_test_cap)

In [ ]:
print(seq_len_test_cap)

140


### ***Converting The Target Classes (Sentiment) to Numbers***

In [ ]:
from sklearn.preprocessing import LabelEncoder
from keras.utils.np_utils import to_categorical

#### *Just Reviews*

In [ ]:
le = LabelEncoder()
y_train_le = le.fit_transform(y_train)
y_test_le = le.transform(y_test)
y_train_oh = to_categorical(y_train_le)
y_test_oh = to_categorical(y_test_le)

#### *Reviews with Image Caption*

In [ ]:
le1 = LabelEncoder()
y_train_cap_le = le1.fit_transform(y_train_cap)
y_test_cap_le = le1.transform(y_test_cap)
y_train_cap_oh = to_categorical(y_train_cap_le)
y_test_cap_oh = to_categorical(y_test_cap_le)

### *Splitting off a validation set*

#### *Just Reviews*

In [ ]:
X_train_rest, X_valid, y_train_rest, y_valid = train_test_split(padded_seq_train, y_train_oh, test_size=0.1, random_state=37)

#### *Reviews with Image Caption*

In [ ]:
X_train_cap_rest, X_valid_cap, y_train_cap_rest, y_valid_cap = train_test_split(padded_seq_train_cap, y_train_cap_oh, test_size=0.1, random_state=37)

In [ ]:
X_train_cap_rest.shape

(2430, 140)

In [ ]:
X_valid_cap.shape

(270, 140)